checks:
  python:
    code_rating: true
    duplicate_code: true

build:
  environment:
    python:
      version: 3.8.8
      virtualenv: true

  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - py-scrutinizer-run
          -
            command: pylint-run
            use_website_config: true
filter:
  excluded_paths:
    - '*/tests/*'
    - '*/docs/*'
  dependency_paths:
    - 'lib/*'
